--- 
- name: WordPress installation
  hosts: webserver
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: apache2
        state: latest

    - name: Start apache2 webserver
      service: 
        name: apache2
        state: started

    - name: Add source repository
      apt_repository:
        repo: ppa:ondrej/php

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install php and required php modules
      apt:
        name:
          - php
          - libapache2-mod-php7.0
          - php-mysql
        state: present

    - name: Reload apache configuration
      service:
        name: apache2
        state: reloaded

    - name: Install python and pip
      apt: 
        name:
          - python-pip
          - python-mysqldb
        state: present


    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install mysql
      apt:
        name: mysql-server

    - name: Start mysql server
      service:
        name: mysql
        state: started

    - name: Install mysql-python package
      pip:
        name: PyMySQL
        state: present

    - name: Create a database for wordpress
      mysql_db:
        name: wordpressdb
        state: present

    - name: Create a user for the database and give privileges
      mysql_user:
        name: wpuser
        password: worduserpass123
        priv: '*.*:ALL'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install php modules for wordpress
      apt:
        name:
          - php7.2-curl
          - php7.2-gd
          - php7.2-mbstring
          - php7.2-xml
          - php7.2-xmlrpc
          - php7.2-soap
          - php7.2-intl
          - php7.2-zip
          - php7.0-mysql
        state: present

    - name: Reload apache2 webserver
      service: 
        name: apache2
        state: reloaded

    - name: Download AND extract WordPress files
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        remote_src: yes
        dest: /var/www/html
        owner: www-data
        group: www-data

    - name: Copy wordpress configuration
      template:
        src: ./wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: 0774

    - name: Change directory permissions to www-data
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Copy apache configuration file
      template:
        src: ./000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        owner: www-data
        group: www-data
        mode: 0774

    - name: Reload apache2 webserver
      service:
        name: apache2
        state: reloaded

    - name: Remove unnecessary files
      file:
        state: absent
        path: /var/www/html/wordpress-*
        remote_src: yes
